version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server.dev
    volumes:
      - ./server/src:/app/src
    ports:
      - "8000:8000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    volumes:
      - ./client/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - SERVER_HOST=http://server:8000